// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Person.proto
// Protobuf Java Version: 4.31.1

package org.example;

@com.google.protobuf.Generated
public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.org.example.Person.Name name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.org.example.Person.Name name = 2;</code>
   * @return The name.
   */
  org.example.Person.Name getName();
  /**
   * <code>.org.example.Person.Name name = 2;</code>
   */
  org.example.Person.NameOrBuilder getNameOrBuilder();

  /**
   * <code>.org.example.Person.Email email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>.org.example.Person.Email email = 3;</code>
   * @return The email.
   */
  org.example.Person.Email getEmail();
  /**
   * <code>.org.example.Person.Email email = 3;</code>
   */
  org.example.Person.EmailOrBuilder getEmailOrBuilder();

  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<org.example.Person.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  org.example.Person.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends org.example.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  org.example.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
