// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

// Protobuf Java Version: 3.25.6
package org.example;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Person_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_Person_Name_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\013org.example\"\220\001\n\006Person\022\n" +
      "\n\002id\030\001 \001(\005\022&\n\004name\030\002 \001(\0132\030.org.example.P" +
      "erson.Name\022\r\n\005test1\030\003 \001(\001\022\r\n\005test2\030\004 \001(\r" +
      "\022\r\n\005test3\030\005 \001(\002\032%\n\004Name\022\r\n\005value\030\001 \001(\t\022\016" +
      "\n\006value2\030\002 \001(\tB\017\n\013org.exampleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Test1", "Test2", "Test3", });
    internal_static_org_example_Person_Name_descriptor =
      internal_static_org_example_Person_descriptor.getNestedTypes().get(0);
    internal_static_org_example_Person_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_Person_Name_descriptor,
        new java.lang.String[] { "Value", "Value2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
