// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Person.proto
// Protobuf Java Version: 4.31.1

package org.example;

/**
 * Protobuf type {@code org.example.Person}
 */
@com.google.protobuf.Generated
public final class Person extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Person.class.getName());
  }
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    phones_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.PersonOuterClass.internal_static_org_example_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.PersonOuterClass.internal_static_org_example_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.Person.class, org.example.Person.Builder.class);
  }

  public interface NameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.Person.Name)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code org.example.Person.Name}
   */
  public static final class Name extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.Person.Name)
      NameOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Name.class.getName());
    }
    // Use Name.newBuilder() to construct.
    private Name(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Name() {
      value_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_Name_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_Name_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.Person.Name.class, org.example.Person.Name.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.Person.Name)) {
        return super.equals(obj);
      }
      org.example.Person.Name other = (org.example.Person.Name) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.Person.Name parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.Name parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.Name parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.Name parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.Name parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.Name parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.Name parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Person.Name parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.Person.Name parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.Person.Name parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.Person.Name parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Person.Name parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.Person.Name prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.Person.Name}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.Person.Name)
        org.example.Person.NameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_Name_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_Name_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.Person.Name.class, org.example.Person.Name.Builder.class);
      }

      // Construct using org.example.Person.Name.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_Name_descriptor;
      }

      @java.lang.Override
      public org.example.Person.Name getDefaultInstanceForType() {
        return org.example.Person.Name.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.Person.Name build() {
        org.example.Person.Name result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.Person.Name buildPartial() {
        org.example.Person.Name result = new org.example.Person.Name(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.Person.Name result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.Person.Name) {
          return mergeFrom((org.example.Person.Name)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.Person.Name other) {
        if (other == org.example.Person.Name.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.Person.Name)
    }

    // @@protoc_insertion_point(class_scope:org.example.Person.Name)
    private static final org.example.Person.Name DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.Person.Name();
    }

    public static org.example.Person.Name getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Name>
        PARSER = new com.google.protobuf.AbstractParser<Name>() {
      @java.lang.Override
      public Name parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Name> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Name> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.Person.Name getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.Person.Email)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code org.example.Person.Email}
   */
  public static final class Email extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.Person.Email)
      EmailOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Email.class.getName());
    }
    // Use Email.newBuilder() to construct.
    private Email(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Email() {
      value_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_Email_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_Email_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.Person.Email.class, org.example.Person.Email.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.Person.Email)) {
        return super.equals(obj);
      }
      org.example.Person.Email other = (org.example.Person.Email) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.Person.Email parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.Email parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.Email parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.Email parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.Email parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.Email parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.Email parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Person.Email parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.Person.Email parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.Person.Email parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.Person.Email parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Person.Email parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.Person.Email prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.Person.Email}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.Person.Email)
        org.example.Person.EmailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_Email_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_Email_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.Person.Email.class, org.example.Person.Email.Builder.class);
      }

      // Construct using org.example.Person.Email.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_Email_descriptor;
      }

      @java.lang.Override
      public org.example.Person.Email getDefaultInstanceForType() {
        return org.example.Person.Email.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.Person.Email build() {
        org.example.Person.Email result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.Person.Email buildPartial() {
        org.example.Person.Email result = new org.example.Person.Email(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.Person.Email result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.Person.Email) {
          return mergeFrom((org.example.Person.Email)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.Person.Email other) {
        if (other == org.example.Person.Email.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.Person.Email)
    }

    // @@protoc_insertion_point(class_scope:org.example.Person.Email)
    private static final org.example.Person.Email DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.Person.Email();
    }

    public static org.example.Person.Email getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Email>
        PARSER = new com.google.protobuf.AbstractParser<Email>() {
      @java.lang.Override
      public Email parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Email> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Email> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.Person.Email getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.Person.PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string number = 1;</code>
     * @return Whether the number field is set.
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();
  }
  /**
   * Protobuf type {@code org.example.Person.PhoneNumber}
   */
  public static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.Person.PhoneNumber)
      PhoneNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        PhoneNumber.class.getName());
    }
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
      number_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.Person.PhoneNumber.class, org.example.Person.PhoneNumber.Builder.class);
    }

    private int bitField0_;
    public static final int NUMBER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object number_ = "";
    /**
     * <code>optional string number = 1;</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>optional string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, number_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, number_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.Person.PhoneNumber)) {
        return super.equals(obj);
      }
      org.example.Person.PhoneNumber other = (org.example.Person.PhoneNumber) obj;

      if (hasNumber() != other.hasNumber()) return false;
      if (hasNumber()) {
        if (!getNumber()
            .equals(other.getNumber())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNumber()) {
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.Person.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Person.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Person.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Person.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.Person.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.Person.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Person.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.Person.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.Person.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.Person.PhoneNumber)
        org.example.Person.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.Person.PhoneNumber.class, org.example.Person.PhoneNumber.Builder.class);
      }

      // Construct using org.example.Person.PhoneNumber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        number_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.PersonOuterClass.internal_static_org_example_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public org.example.Person.PhoneNumber getDefaultInstanceForType() {
        return org.example.Person.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.Person.PhoneNumber build() {
        org.example.Person.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.Person.PhoneNumber buildPartial() {
        org.example.Person.PhoneNumber result = new org.example.Person.PhoneNumber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.Person.PhoneNumber result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.number_ = number_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.Person.PhoneNumber) {
          return mergeFrom((org.example.Person.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.Person.PhoneNumber other) {
        if (other == org.example.Person.PhoneNumber.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          number_ = other.number_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                number_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 1;</code>
       * @return Whether the number field is set.
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        number_ = getDefaultInstance().getNumber();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.Person.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:org.example.Person.PhoneNumber)
    private static final org.example.Person.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.Person.PhoneNumber();
    }

    public static org.example.Person.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.Person.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private org.example.Person.Name name_;
  /**
   * <code>.org.example.Person.Name name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.example.Person.Name name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public org.example.Person.Name getName() {
    return name_ == null ? org.example.Person.Name.getDefaultInstance() : name_;
  }
  /**
   * <code>.org.example.Person.Name name = 2;</code>
   */
  @java.lang.Override
  public org.example.Person.NameOrBuilder getNameOrBuilder() {
    return name_ == null ? org.example.Person.Name.getDefaultInstance() : name_;
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private org.example.Person.Email email_;
  /**
   * <code>.org.example.Person.Email email = 3;</code>
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.example.Person.Email email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public org.example.Person.Email getEmail() {
    return email_ == null ? org.example.Person.Email.getDefaultInstance() : email_;
  }
  /**
   * <code>.org.example.Person.Email email = 3;</code>
   */
  @java.lang.Override
  public org.example.Person.EmailOrBuilder getEmailOrBuilder() {
    return email_ == null ? org.example.Person.Email.getDefaultInstance() : email_;
  }

  public static final int PHONES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<org.example.Person.PhoneNumber> phones_;
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.Person.PhoneNumber> getPhonesList() {
    return phones_;
  }
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList() {
    return phones_;
  }
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public int getPhonesCount() {
    return phones_.size();
  }
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public org.example.Person.PhoneNumber getPhones(int index) {
    return phones_.get(index);
  }
  /**
   * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public org.example.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index) {
    return phones_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getName());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getEmail());
    }
    for (int i = 0; i < phones_.size(); i++) {
      output.writeMessage(4, phones_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getName());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEmail());
    }
    for (int i = 0; i < phones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, phones_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.Person)) {
      return super.equals(obj);
    }
    org.example.Person other = (org.example.Person) obj;

    if (getId()
        != other.getId()) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (!getPhonesList()
        .equals(other.getPhonesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (getPhonesCount() > 0) {
      hash = (37 * hash) + PHONES_FIELD_NUMBER;
      hash = (53 * hash) + getPhonesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.Person)
      org.example.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.Person.class, org.example.Person.Builder.class);
    }

    // Construct using org.example.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetNameFieldBuilder();
        internalGetEmailFieldBuilder();
        internalGetPhonesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      name_ = null;
      if (nameBuilder_ != null) {
        nameBuilder_.dispose();
        nameBuilder_ = null;
      }
      email_ = null;
      if (emailBuilder_ != null) {
        emailBuilder_.dispose();
        emailBuilder_ = null;
      }
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
      } else {
        phones_ = null;
        phonesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.PersonOuterClass.internal_static_org_example_Person_descriptor;
    }

    @java.lang.Override
    public org.example.Person getDefaultInstanceForType() {
      return org.example.Person.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.Person build() {
      org.example.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.Person buildPartial() {
      org.example.Person result = new org.example.Person(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.Person result) {
      if (phonesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phones_ = phones_;
      } else {
        result.phones_ = phonesBuilder_.build();
      }
    }

    private void buildPartial0(org.example.Person result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = nameBuilder_ == null
            ? name_
            : nameBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.email_ = emailBuilder_ == null
            ? email_
            : emailBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.Person) {
        return mergeFrom((org.example.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.Person other) {
      if (other == org.example.Person.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasEmail()) {
        mergeEmail(other.getEmail());
      }
      if (phonesBuilder_ == null) {
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
      } else {
        if (!other.phones_.isEmpty()) {
          if (phonesBuilder_.isEmpty()) {
            phonesBuilder_.dispose();
            phonesBuilder_ = null;
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000008);
            phonesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPhonesFieldBuilder() : null;
          } else {
            phonesBuilder_.addAllMessages(other.phones_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetEmailFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              org.example.Person.PhoneNumber m =
                  input.readMessage(
                      org.example.Person.PhoneNumber.parser(),
                      extensionRegistry);
              if (phonesBuilder_ == null) {
                ensurePhonesIsMutable();
                phones_.add(m);
              } else {
                phonesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private org.example.Person.Name name_;
    private com.google.protobuf.SingleFieldBuilder<
        org.example.Person.Name, org.example.Person.Name.Builder, org.example.Person.NameOrBuilder> nameBuilder_;
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     * @return The name.
     */
    public org.example.Person.Name getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? org.example.Person.Name.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     */
    public Builder setName(org.example.Person.Name value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
      } else {
        nameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     */
    public Builder setName(
        org.example.Person.Name.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     */
    public Builder mergeName(org.example.Person.Name value) {
      if (nameBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          name_ != null &&
          name_ != org.example.Person.Name.getDefaultInstance()) {
          getNameBuilder().mergeFrom(value);
        } else {
          name_ = value;
        }
      } else {
        nameBuilder_.mergeFrom(value);
      }
      if (name_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = null;
      if (nameBuilder_ != null) {
        nameBuilder_.dispose();
        nameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     */
    public org.example.Person.Name.Builder getNameBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     */
    public org.example.Person.NameOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            org.example.Person.Name.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.org.example.Person.Name name = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.example.Person.Name, org.example.Person.Name.Builder, org.example.Person.NameOrBuilder> 
        internalGetNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.example.Person.Name, org.example.Person.Name.Builder, org.example.Person.NameOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private org.example.Person.Email email_;
    private com.google.protobuf.SingleFieldBuilder<
        org.example.Person.Email, org.example.Person.Email.Builder, org.example.Person.EmailOrBuilder> emailBuilder_;
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     * @return The email.
     */
    public org.example.Person.Email getEmail() {
      if (emailBuilder_ == null) {
        return email_ == null ? org.example.Person.Email.getDefaultInstance() : email_;
      } else {
        return emailBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     */
    public Builder setEmail(org.example.Person.Email value) {
      if (emailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        email_ = value;
      } else {
        emailBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     */
    public Builder setEmail(
        org.example.Person.Email.Builder builderForValue) {
      if (emailBuilder_ == null) {
        email_ = builderForValue.build();
      } else {
        emailBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     */
    public Builder mergeEmail(org.example.Person.Email value) {
      if (emailBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          email_ != null &&
          email_ != org.example.Person.Email.getDefaultInstance()) {
          getEmailBuilder().mergeFrom(value);
        } else {
          email_ = value;
        }
      } else {
        emailBuilder_.mergeFrom(value);
      }
      if (email_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     */
    public Builder clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000004);
      email_ = null;
      if (emailBuilder_ != null) {
        emailBuilder_.dispose();
        emailBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     */
    public org.example.Person.Email.Builder getEmailBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetEmailFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     */
    public org.example.Person.EmailOrBuilder getEmailOrBuilder() {
      if (emailBuilder_ != null) {
        return emailBuilder_.getMessageOrBuilder();
      } else {
        return email_ == null ?
            org.example.Person.Email.getDefaultInstance() : email_;
      }
    }
    /**
     * <code>.org.example.Person.Email email = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.example.Person.Email, org.example.Person.Email.Builder, org.example.Person.EmailOrBuilder> 
        internalGetEmailFieldBuilder() {
      if (emailBuilder_ == null) {
        emailBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.example.Person.Email, org.example.Person.Email.Builder, org.example.Person.EmailOrBuilder>(
                getEmail(),
                getParentForChildren(),
                isClean());
        email_ = null;
      }
      return emailBuilder_;
    }

    private java.util.List<org.example.Person.PhoneNumber> phones_ =
      java.util.Collections.emptyList();
    private void ensurePhonesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        phones_ = new java.util.ArrayList<org.example.Person.PhoneNumber>(phones_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.Person.PhoneNumber, org.example.Person.PhoneNumber.Builder, org.example.Person.PhoneNumberOrBuilder> phonesBuilder_;

    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public java.util.List<org.example.Person.PhoneNumber> getPhonesList() {
      if (phonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phones_);
      } else {
        return phonesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public int getPhonesCount() {
      if (phonesBuilder_ == null) {
        return phones_.size();
      } else {
        return phonesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public org.example.Person.PhoneNumber getPhones(int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);
      } else {
        return phonesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder setPhones(
        int index, org.example.Person.PhoneNumber value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder setPhones(
        int index, org.example.Person.PhoneNumber.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.set(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(org.example.Person.PhoneNumber value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(
        int index, org.example.Person.PhoneNumber value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(index, value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(
        org.example.Person.PhoneNumber.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(
        int index, org.example.Person.PhoneNumber.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addAllPhones(
        java.lang.Iterable<? extends org.example.Person.PhoneNumber> values) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
      } else {
        phonesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder clearPhones() {
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public Builder removePhones(int index) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.remove(index);
        onChanged();
      } else {
        phonesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public org.example.Person.PhoneNumber.Builder getPhonesBuilder(
        int index) {
      return internalGetPhonesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public org.example.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
        int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);  } else {
        return phonesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public java.util.List<? extends org.example.Person.PhoneNumberOrBuilder> 
         getPhonesOrBuilderList() {
      if (phonesBuilder_ != null) {
        return phonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phones_);
      }
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public org.example.Person.PhoneNumber.Builder addPhonesBuilder() {
      return internalGetPhonesFieldBuilder().addBuilder(
          org.example.Person.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public org.example.Person.PhoneNumber.Builder addPhonesBuilder(
        int index) {
      return internalGetPhonesFieldBuilder().addBuilder(
          index, org.example.Person.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.Person.PhoneNumber phones = 4;</code>
     */
    public java.util.List<org.example.Person.PhoneNumber.Builder> 
         getPhonesBuilderList() {
      return internalGetPhonesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.Person.PhoneNumber, org.example.Person.PhoneNumber.Builder, org.example.Person.PhoneNumberOrBuilder> 
        internalGetPhonesFieldBuilder() {
      if (phonesBuilder_ == null) {
        phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.example.Person.PhoneNumber, org.example.Person.PhoneNumber.Builder, org.example.Person.PhoneNumberOrBuilder>(
                phones_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        phones_ = null;
      }
      return phonesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.example.Person)
  }

  // @@protoc_insertion_point(class_scope:org.example.Person)
  private static final org.example.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.Person();
  }

  public static org.example.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

