// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Person.proto
// Protobuf Java Version: 4.31.1

package org.example;

@com.google.protobuf.Generated
public final class PersonOuterClass {
  private PersonOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      PersonOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Person_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_Person_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Person_Email_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_Person_Email_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_Person_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\013org.example\"\365\001\n\006Person\022\n" +
      "\n\002id\030\001 \001(\005\022&\n\004name\030\002 \001(\0132\030.org.example.P" +
      "erson.Name\022(\n\005email\030\003 \001(\0132\031.org.example." +
      "Person.Email\022/\n\006phones\030\004 \003(\0132\037.org.examp" +
      "le.Person.PhoneNumber\032\025\n\004Name\022\r\n\005value\030\001" +
      " \001(\t\032\026\n\005Email\022\r\n\005value\030\001 \001(\t\032-\n\013PhoneNum" +
      "ber\022\023\n\006number\030\001 \001(\tH\000\210\001\001B\t\n\007_numberB\017\n\013o" +
      "rg.exampleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Phones", });
    internal_static_org_example_Person_Name_descriptor =
      internal_static_org_example_Person_descriptor.getNestedTypes().get(0);
    internal_static_org_example_Person_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_Person_Name_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_org_example_Person_Email_descriptor =
      internal_static_org_example_Person_descriptor.getNestedTypes().get(1);
    internal_static_org_example_Person_Email_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_Person_Email_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_org_example_Person_PhoneNumber_descriptor =
      internal_static_org_example_Person_descriptor.getNestedTypes().get(2);
    internal_static_org_example_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
