// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

// Protobuf Java Version: 3.25.6
package org.example;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.org.example.Person.Name name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.org.example.Person.Name name = 2;</code>
   * @return The name.
   */
  org.example.Person.Name getName();
  /**
   * <code>.org.example.Person.Name name = 2;</code>
   */
  org.example.Person.NameOrBuilder getNameOrBuilder();

  /**
   * <code>double test1 = 3;</code>
   * @return The test1.
   */
  double getTest1();

  /**
   * <code>uint32 test2 = 4;</code>
   * @return The test2.
   */
  int getTest2();

  /**
   * <code>float test3 = 5;</code>
   * @return The test3.
   */
  float getTest3();
}
